### ISSUE TITLE
help(smisk) dumps core

### ISSUE THREAD

**Issue by ddarah** [rsms/smisk#5]
(smisk)[sam@sam smisk]$ python
Python 2.6.4 (r264:75706, Jun  4 2010, 18:20:16) 
[GCC 4.4.4 20100503 (Red Hat 4.4.4-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import smisk
> > > help(smisk)
> > > python: Modules/gcmodule.c:277: visit_decref: Assertion `gc->gc.gc_refs != 0' failed.
> > > Aborted (core dumped)

Help me... i am trying out smisk on my fedora13 laptop(32 bit). All the other details are there above.

Sam

**Comment by rsms** [comment]
Interesting. First off, Smisk has not been properly tested with Python 2.6 yet, so this might be as "simple" as a reference counting bug in Python or Smisk surfaced due to changes/corrections in >2.6.2 (I do know Smisk runs on 2.6.2).

I'll look into it — you might just have found the first bug in Smisk since March 2009!

**Comment by ddarah** [comment]
Well thanks.

**Comment by btbytes** [comment]
This appears to be a Python bug. There are similar reports associated with PyQt4, uwsgi etc.,
